### ISSUE TITLE
[INVALID] Crash on 1.9 with forge 1859

### ISSUE THREAD

**Issue by Jiraiyah** [chylex/Better-Sprinting#12]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (ChunkAnimator-MC1.9-1.1.jar)
  LoadingPlugin (FastLeafDecay-MC1.9-1.2.jar)
  Reborn Core ASM (RebornCore-1.9-2.0.4.46-universal.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 4/12/16 5:41 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access field net.minecraftforge.common.config.Property.comment from class chylex.bettersprinting.BetterSprintingConfig
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:559)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:240)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:434)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraftforge.common.config.Property.comment from class chylex.bettersprinting.BetterSprintingConfig
    at chylex.bettersprinting.BetterSprintingConfig.setComment(BetterSprintingConfig.java:51)
    at chylex.bettersprinting.client.ClientSettings.reload(ClientSettings.java:39)
    at chylex.bettersprinting.client.ClientProxy.loadSidedConfig(ClientProxy.java:20)
    at chylex.bettersprinting.BetterSprintingConfig.reload(BetterSprintingConfig.java:30)
    at chylex.bettersprinting.BetterSprintingConfig.<init>(BetterSprintingConfig.java:21)
    at chylex.bettersprinting.BetterSprintingMod.onPreInit(BetterSprintingMod.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2937840768 bytes (2801 MB) / 3207856128 bytes (3059 MB) up to 3207856128 bytes (3059 MB)
    JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -Xms3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.23 Powered by Forge 12.16.0.1859 27 mods loaded, 27 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{8.0.99.99} [Forge Mod Loader](forge-1.9-12.16.0.1859-1.9.jar) 
    UCH Forge{12.16.0.1859} [Minecraft Forge](forge-1.9-12.16.0.1859-1.9.jar) 
    UCH betterbuilderswands{0.5.4} [Better Builder's Wands](BetterBuildersWands-0.5.4-1.9r106+81accd9.jar) 
    UCE BetterSprinting{1.1.4} [Better Sprinting](BetterSprinting  MC-1.9  v1.1.4.jar) 
    UCH BiomesOPlenty{4.0.0.1985} [Biomes O' Plenty](BiomesOPlenty-1.9-4.0.0.1985-universal.jar) 
    UCH samsbucketblocks{1.0.1} [Bucket Storage](BucketBlocks-1.9-1.0.1.jar) 
    UCH buildingbrickscompatvanilla{1.9-1.4.5} [Building Bricks Vanilla Compat](BuildingBricks-1.9-1.4.5.jar) 
    UCH buildingbricks{1.9-1.4.5} [Building Bricks](BuildingBricks-1.9-1.4.5.jar) 
    UCH chisel{@VERSION@} [Chisel](Chisel-MC1.9-0.0.4.13.jar) 
    UCH mcmultipart{1.1.1} [MCMultiPart](MCMultiPart-1.1.1-universal.jar) 
    UCH chiselsandbits{9.11} [Chisels & Bits](chiselsandbits-9.11.jar) 
    UCH ChunkAnimator{1.1} [Chunk Animator](ChunkAnimator-MC1.9-1.1.jar) 
    UCH FFS{1.9-1.5.1.1.2} [Fancy Fluid Storage](Fancy Fluid Storage-1.9-1.5.1.1.2.jar) 
    UCH FastLeaveDecay{1.1} [Fast Leave Decay](FastLeafDecay-MC1.9-1.2.jar) 
    UCH graves{1.9-b8-universal} [Graves Mod](graves-1.9-b8-universal.jar) 
    UCH IronChest{6.0.132.776} [Iron Chest](ironchest-1.9-6.0.132.776.jar) 
    UCH JEI{3.2.10.185} [Just Enough Items](jei_1.9-3.2.10.185.jar) 
    UCH journeymap{1.9-5.1.6b1} [JourneyMap](journeymap-1.9-5.1.6b1-unlimited.jar) 
    UCH mantle{1.9-0.9.4.jenkins114} [Mantle](Mantle-1.9-0.9.4.jar) 
    UCH progressiveautomation{1.6.38} [Progressive Automation](ProgressiveAutomation-1.9-1.6.38.jar) 
    UCH reborncore{2.0.4.46} [RebornCore](RebornCore-1.9-2.0.4.46-universal.jar) 
    UCH RTG{1.9-0.0.5} [Realistic Terrain Generation](RTG-1.9-0.0.5.jar) 
    UCH tconstruct{1.9-2.2.2.jenkins156} [Tinkers' Construct](TConstruct-1.9-2.2.2.jar) 
    UCH tomtom{@Version@} [TomTom](tomtom-1.9-b5-universal.jar) 
    UCH Trashcans{2.0.2} [Trashcans](Trashcans-1.9-2.0.2.jar) 
    UCH villageinfo{1.0.0} [Village Info](VillageInfoMod-1.9-7.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (ChunkAnimator-MC1.9-1.1.jar)
  lumien.chunkanimator.asm.ClassTransformer
LoadingPlugin (FastLeafDecay-MC1.9-1.2.jar)
  lumien.fastleavedecay.asm.ClassTransformer
Reborn Core ASM (RebornCore-1.9-2.0.4.46-universal.jar)
  reborncore.asm.RebornClassTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 361.75' Renderer: 'GeForce GTX 650/PCIe/SSE2'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)

**Comment by Jiraiyah** [comment]
at chylex.bettersprinting.BetterSprintingConfig.setComment(BetterSprintingConfig.java:51)
at chylex.bettersprinting.client.ClientSettings.reload(ClientSettings.java:39)
at chylex.bettersprinting.client.ClientProxy.loadSidedConfig(ClientProxy.java:20)
at chylex.bettersprinting.BetterSprintingConfig.reload(BetterSprintingConfig.java:30)
at chylex.bettersprinting.BetterSprintingConfig.(BetterSprintingConfig.java:21)
at chylex.bettersprinting.BetterSprintingMod.onPreInit(BetterSprintingMod.java:28)

**Comment by chylex** [comment]
Update to 1.1.4a.
