### ISSUE TITLE
[1.16.1] Server crash

### ISSUE THREAD

**Issue by C0rn3j** [chylex/Better-Sprinting#59]
Mod loads fine on client, but not on server.
```
forge-1.16.1-32.0.106
BetterSprinting-1.16.1-v3.2.0.jar
java-8-openjdk/jre
```

```
Starting Minecraft server...
2020-08-04 23:31:51,026 main WARN Advanced terminal features are not available in this environment
[23:31:51] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 32.0.106, --fml.mcpVersion, 20200625.160719, --fml.mcVersion, 1.16.1, --fml.forgeGroup, net.minecraftforge, nogui]
[23:31:51] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 6.1.1+74+master.966c698 starting: java version 1.8.0_262 by Oracle Corporation
[23:31:51] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[23:31:51] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/root/server1.16.1/libraries/org/spongepowered/mixin/0.8/mixin-0.8.jar Service=ModLauncher Env=SERVER
[23:31:51] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, ., nogui]
[23:31:58] [modloading-worker-1/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 32.0.106, for MC 1.16.1 with MCP 20200625.160719
[23:31:58] [modloading-worker-1/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v32.0.106 Initialized                                                                                                                                       
[23:31:59] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json                                                          
[23:32:00] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Found status: BETA Current: 32.0.106 Target: 32.0.106                                                                                                                   
[23:32:00] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [bettersprinting] Starting version check at https://raw.githubusercontent.com/chylex/Better-Sprinting/master/UpdateInfo.json                                                    
[23:32:00] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [bettersprinting] Found status: UP_TO_DATE Current: 3.2.0 Target: null                                                                                                          
[23:32:00] [main/INFO] [mojang/YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'                         
[23:32:01] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[23:32:01] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]                                                                                       
[23:32:01] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]                                                                                           
[23:32:01] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]                                                        
[23:32:01] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]                                                                     
[23:32:01] [main/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, forge-1.16.1-32.0.106-universal.jar, BetterSprinting-1.16.1-v3.2.0.jar
[23:32:02] [Worker-Main-11/INFO] [minecraft/RecipeManager]: Loaded 7 recipes                                                                                                                                                                      
[23:32:02] [Worker-Main-11/INFO] [minecraft/AdvancementList]: Loaded 927 advancements                                                                                                                                                             
[23:32:03] [Server thread/INFO] [minecraft/DedicatedServer]: Starting minecraft server version 1.16.1                                                                                                                                             
[23:32:03] [Server thread/INFO] [minecraft/DedicatedServer]: Loading properties                                                                                                                                                                   
[23:32:03] [Server thread/INFO] [minecraft/DedicatedServer]: Default game type: SURVIVAL                                                                                                                                                          
[23:32:03] [Server thread/INFO] [minecraft/DedicatedServer]: Generating keypair                                                                                                                                                                   
[23:32:03] [Server thread/INFO] [minecraft/DedicatedServer]: Starting Minecraft server on *:25565                                                                                                                                                 
[23:32:03] [Server thread/INFO] [minecraft/NetworkSystem]: Using epoll channel type                                                                                                                                                               
[23:32:03] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Configuration file ./world/serverconfig/forge-server.toml is not correct. Correcting
[23:32:03] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server was corrected from null to SimpleCommentedConfig:{}                                                                                                         
[23:32:03] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.removeErroringEntities was corrected from null to false                                                                                                     
[23:32:03] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.removeErroringTileEntities was corrected from null to false                                                                                                 
[23:32:03] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.fullBoundingBoxLadders was corrected from null to false                                                                                                     
[23:32:03] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.zombieBaseSummonChance was corrected from null to 0.1                                                                                                       
[23:32:03] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.zombieBabyChance was corrected from null to 0.05                                                                                                            
[23:32:03] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.logCascadingWorldGeneration was corrected from null to true                                                                                                 
[23:32:03] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.fixVanillaCascading was corrected from null to false                                                                                                        
[23:32:03] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.dimensionUnloadQueueDelay was corrected from null to 0                                                                                                      
[23:32:03] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.clumpingThreshold was corrected from null to 64                                                                                                             
[23:32:03] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.treatEmptyTagsAsAir was corrected from null to false                                                                                                        
[23:32:03] [Server thread/WARN] [ne.mi.co.ForgeConfigSpec/CORE]: Incorrect key server.fixAdvancementLoading was corrected from null to true                                                                                                       
[23:32:03] [Server thread/INFO] [minecraft/DedicatedServer]: Preparing level "world"
[23:32:09] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing start region for dimension minecraft:overworld                                                                                                                             
[23:32:09] [Worker-Main-9/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 0%                                                                                                                                                  
...
[23:32:24] [Worker-Main-14/INFO] [minecraft/LoggingChunkStatusListener]: Preparing spawn area: 94%
[23:32:25] [Server thread/INFO] [minecraft/LoggingChunkStatusListener]: Time elapsed: 15467 ms
[23:32:25] [Server thread/INFO] [minecraft/DedicatedServer]: Done (21.137s)! For help, type "help"
[23:32:25] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: net.minecraftforge.fml.event.server.FMLServerStartingEvent.getCommandDispatcher()Lcom/mojang/brigadier/CommandDispatcher;
        Index: 1
        Listeners:
                0: NORMAL
                1: ASM: class chylex.bettersprinting.server.ServerSetup onServerStarting(Lnet/minecraftforge/fml/event/server/FMLServerStartingEvent;)V
java.lang.NoSuchMethodError: net.minecraftforge.fml.event.server.FMLServerStartingEvent.getCommandDispatcher()Lcom/mojang/brigadier/CommandDispatcher;
        at chylex.bettersprinting.server.ServerSetup.onServerStarting(ServerSetup.java:20)
        at net.minecraftforge.eventbus.ASMEventHandler_3_ServerSetup_onServerStarting_FMLServerStartingEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
        at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:104)
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:200)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:622)
        at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230)
        at java.lang.Thread.run(Thread.java:748)

[23:32:25] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraftforge.fml.event.server.FMLServerStartingEvent.getCommandDispatcher()Lcom/mojang/brigadier/CommandDispatcher;
        at chylex.bettersprinting.server.ServerSetup.onServerStarting(ServerSetup.java:20) ~[?:3.2.0] {re:classloading}
        at net.minecraftforge.eventbus.ASMEventHandler_3_ServerSetup_onServerStarting_FMLServerStartingEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
        at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:104) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:200) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:622) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262] {}
Minecraft server exited, waiting 10 seconds before re-launching it...
```

**Comment by chylex** [comment]
Forge 1.16.1 is still in development and is introducing breaking changes, so I think I will wait until the first recommended release to fix the crash. Until then you could downgrade Forge to version 32.0.66, but be wary of using unstable and old versions in general.

If your intention is to disable Better Sprinting or change the settings server-side, unfortunately there isn't an official non-Forge version of the server mod, but the network protocol is documented in [ServerNetwork](https://github.com/chylex/Better-Sprinting/blob/master/src/main/java/chylex/bettersprinting/server/ServerNetwork.java) so it's just a matter of responding to a packet sent by the mod on login.

**Comment by chylex** [comment]
1.16.2 is out, I'll release an update now. Caution again though, Forge has just updated and a few things got broken, and Better Sprinting may break again until Forge releases a recommended version.
